### ISSUE TITLE
Confirmation of support for 250S model

### ISSUE THREAD

**Issue by ohmantics** [ohmantics/homebridge-airmega#3]
If anybody is using this plugin with an 250S, please chime in if it's working for you. I don't have one to verify with.

**Comment by ptpittman** [comment]
Chiming! Working perfectly on my 250s. (Well, at least when its wifi isn't constantly fritzing, but that's not on you...)

**Comment by ohmantics** [comment]
Awesome news! Thank you for commenting.

If you have a chance, could you connect with me on the [Homebridge Discord](https://discord.com/invite/Z8jmyvb)? I'm "alexr#3338." I'd like to get some log data from you so I can see what the 250S data looks like.

**Comment by ohmantics** [comment]
> Awesome news! Thank you for commenting.
> 
> If you have a chance, could you connect with me on the [Homebridge Discord](https://discord.com/invite/Z8jmyvb)? I'm "alexr#3338." I'd like to get some log data from you so I can see what the 250S data looks like.

@ptpittman ^^^

**Comment by ptpittman** [comment]
sent you a friend request on discord, the user listing wasn't playing well... just let me know over there what log data you need.

**Comment by okayzac** [comment]
Hello, 
came to say I have some issues. It shows everything working however i cannot control the 250S. The sliders and buttons act like they work but nothing changes on the device. It works with IoCare still. I have been getting the error: ERROR[Airmega Bridge AC46@AIRMEGA 250S@AIRMEGA 250S Purifier@Rotation Speed] characteristic value expected valid finite number and received "undefined" (undefined)

**Comment by ohmantics** [comment]
@okayzac Could you hop on Discord so I can take a look at some debug logs with you?

**Comment by okayzac** [comment]
I dm'ed the log over the other day, msg me if you need me to test anything.
