### ISSUE TITLE
Communicating Status but Not Controlling the Purifier

### ISSUE THREAD

**Issue by Pjichorvath** [ohmantics/homebridge-airmega#36]
I have a 250S, configured and tested with Coway app.  When I use this plugin for HomeKit, I am able to see the status of the device but when I try to control it (like turn it on or off) the device does not respond.  I tried the other plugins on Git but nothing seems to work.

**Comment by ohmantics** [comment]
Please connect with me on the [Homebridge Discord](https://discord.com/invite/Z8jmyvb)? I'm "alexr#3338." I will need to walk through the process of getting log data from you without posting any PII here.

**Comment by Pjichorvath** [comment]
Ok, I just sent a request to connect.

**Comment by Pjichorvath** [comment]
I sent a request to connect on Discord.  I’m Ragnorak#8511.

**Comment by chrisvanhorn** [comment]
I suppose I should have looked a bit harder before posting my separate issue, but I am experiencing the same behavior as you for 1 of my 3 APs.

**Comment by ohmantics** [comment]
Try pulling the 3.4.1 build from npm.

**Comment by chrisvanhorn** [comment]
Same behavior on 3.4.1 for me.

**Comment by ohmantics** [comment]
@chrisvanhorn Stupid question, but after updating, did you restart Homebridge?

**Comment by chrisvanhorn** [comment]
Ah, well I was pretty sure I did after the update but I just uninstalled, reinstalled, logged back in, and restarted and now it does appearing to be working! Good stuff. Thank you very much.
